"""Vector Graph Memory - Hybrid vector-graph database backend for AI agents."""

__version__ = "0.1.0"

# Main agent
from .MemoryAgent import MemoryAgent

# Storage layer
from .VectorGraphStore import VectorGraphStore
from .rag import (
    ConversationTurn,
    DEFAULT_DSPY_RUN_LOG_DIR,
    DEFAULT_EVAL_SOURCE_DIR,
    DEFAULT_EVAL_SUITE_PATH,
    DEFAULT_RAG_ARTIFACT_DIR,
    DEFAULT_RAG_EVAL_WEIGHTS,
    DspyArtifactManifest,
    DspyArtifactStore,
    DspyCompileManager,
    DspyCompileOutcome,
    DspyRagEvalJudge,
    DspyModelIdentity,
    DspyRagSynthesizer,
    DspyRunLogger,
    DspyRunSummary,
    GraphFact,
    LocalEvalSourceResolver,
    RagEvalCase,
    RagEvalBucketReport,
    RagEvalCaseScore,
    RagEvalComponentScores,
    RagEvalJudge,
    RagEvalJudgeResult,
    RagEvalReport,
    RagEvalTraceEntry,
    RagEvalRetrievalRef,
    RagEvalRubric,
    RagEvalWeights,
    RagContext,
    RagContextBuilder,
    RagSynthesisResult,
    RubricRagEvaluator,
    RetrievedPassage,
    build_evaluation_policy_key,
    build_dspy_lm,
    compute_rag_eval_score,
    load_rag_eval_cases,
    normalize_dspy_model_name,
)
from .rules import (
    CanonicalRule,
    CandidateCanonicalRule,
    CandidateRuleEdge,
    CandidateRuleExtractionBundle,
    CandidateSourcePassage,
    CandidateUncertainty,
    DspyRuleExtractor,
    ExpectedCanonicalRule,
    ExpectedRuleEdge,
    ExtractionUncertainty,
    ExtractionScoreReport,
    PydanticAIRuleExtractionPredictor,
    RawPydanticAIRuleExtractionPredictor,
    PreparedRuleExtractionCase,
    RuleExtractionEvaluator,
    RuleExtractionProgram,
    RuleExtractionSignature,
    RuleExtractionComparison,
    RuleExtractionFieldMismatch,
    RuleExtractionRequest,
    RuleExtractionRunner,
    RuleEdge,
    RuleExtractionBundle,
    RulesRulingRequest,
    RulesRulingResult,
    RuleCitation,
    RuleReference,
    PrecedenceEntry,
    DeterministicPilotRulingEngine,
    LivePilotRulingEngine,
    LivePilotRulingInspection,
    PilotCaseMatch,
    PilotRulingEvalCase,
    PilotRulingEvalCaseReport,
    PilotRulingEvalComponentScores,
    PilotRulingEvalReport,
    PilotRulingEvaluator,
    PilotSeedInference,
    PilotSeedScore,
    RetrievedEvidenceEdge,
    RetrievedEvidenceNode,
    RetrievedRulingEvidence,
    ScopedSourceDocument,
    SourcePassage,
    build_request_from_reference_bundle,
    build_seed_edge_records,
    build_seed_manifest,
    build_seed_node_records,
    compile_rule_extractor,
    compare_rule_extractions,
    write_seed_fixture,
    load_reference_bundle_from_seed_fixture,
    load_rule_bundle_from_seed_manifest,
    load_bundle_from_seed_records,
    load_pilot_ruling_eval_cases,
    load_seti_pilot_bundles,
    make_rule_extraction_program,
    normalize_candidate_bundle,
)

# Schemas
from .schemas import (
    NodeMetadata,
    EdgeMetadata,
    AuditEntry,
    SimilarNode,
)

# Configuration
from .config import (
    MemoryConfig,
    MemoryTriggerConfig,
    AuditConfig,
    VectorGraphConfig,
)

# Audit backends
from .audit import (
    AuditBackend,
    JSONLAuditBackend,
    MongoAuditBackend,
)

__all__ = [
    # Version
    "__version__",
    # Main API
    "MemoryAgent",
    "VectorGraphStore",
    "ConversationTurn",
    "DEFAULT_DSPY_RUN_LOG_DIR",
    "DEFAULT_EVAL_SOURCE_DIR",
    "DEFAULT_EVAL_SUITE_PATH",
    "DEFAULT_RAG_ARTIFACT_DIR",
    "DEFAULT_RAG_EVAL_WEIGHTS",
    "DspyArtifactManifest",
    "DspyArtifactStore",
    "DspyCompileManager",
    "DspyCompileOutcome",
    "DspyRagEvalJudge",
    "DspyModelIdentity",
    "DspyRagSynthesizer",
    "DspyRunLogger",
    "DspyRunSummary",
    "GraphFact",
    "LocalEvalSourceResolver",
    "RagEvalCase",
    "RagEvalBucketReport",
    "RagEvalCaseScore",
    "RagEvalComponentScores",
    "RagEvalJudge",
    "RagEvalJudgeResult",
    "RagEvalReport",
    "RagEvalTraceEntry",
    "RagEvalRetrievalRef",
    "RagEvalRubric",
    "RagEvalWeights",
    "RagContext",
    "RagContextBuilder",
    "RagSynthesisResult",
    "RubricRagEvaluator",
    "RetrievedPassage",
    "build_evaluation_policy_key",
    "build_dspy_lm",
    "compute_rag_eval_score",
    "load_rag_eval_cases",
    "normalize_dspy_model_name",
    "CanonicalRule",
    "CandidateCanonicalRule",
    "CandidateRuleEdge",
    "CandidateRuleExtractionBundle",
    "CandidateSourcePassage",
    "CandidateUncertainty",
    "DspyRuleExtractor",
    "ExpectedCanonicalRule",
    "ExpectedRuleEdge",
    "ExtractionUncertainty",
    "ExtractionScoreReport",
    "PydanticAIRuleExtractionPredictor",
    "RawPydanticAIRuleExtractionPredictor",
    "PreparedRuleExtractionCase",
    "RuleExtractionEvaluator",
    "RuleExtractionProgram",
    "RuleExtractionSignature",
    "RuleExtractionComparison",
    "RuleExtractionFieldMismatch",
    "RuleExtractionRequest",
    "RuleExtractionRunner",
    "RuleEdge",
    "RuleExtractionBundle",
    "RulesRulingRequest",
    "RulesRulingResult",
    "RuleCitation",
    "RuleReference",
    "PrecedenceEntry",
    "DeterministicPilotRulingEngine",
    "LivePilotRulingEngine",
    "LivePilotRulingInspection",
    "PilotCaseMatch",
    "PilotRulingEvalCase",
    "PilotRulingEvalCaseReport",
    "PilotRulingEvalComponentScores",
    "PilotRulingEvalReport",
    "PilotRulingEvaluator",
    "PilotSeedInference",
    "PilotSeedScore",
    "RetrievedEvidenceEdge",
    "RetrievedEvidenceNode",
    "RetrievedRulingEvidence",
    "ScopedSourceDocument",
    "SourcePassage",
    "build_request_from_reference_bundle",
    "build_seed_edge_records",
    "build_seed_manifest",
    "build_seed_node_records",
    "compile_rule_extractor",
    "compare_rule_extractions",
    "write_seed_fixture",
    "load_reference_bundle_from_seed_fixture",
    "load_rule_bundle_from_seed_manifest",
    "load_bundle_from_seed_records",
    "load_pilot_ruling_eval_cases",
    "load_seti_pilot_bundles",
    "make_rule_extraction_program",
    "normalize_candidate_bundle",
    # Schemas
    "NodeMetadata",
    "EdgeMetadata",
    "AuditEntry",
    "SimilarNode",
    # Configuration
    "MemoryConfig",
    "MemoryTriggerConfig",
    "AuditConfig",
    "VectorGraphConfig",
    # Audit backends
    "AuditBackend",
    "JSONLAuditBackend",
    "MongoAuditBackend",
]
